"""
Configuration settings for plots generated by saw_analyzer.py.
Structure:
CONFIG = {
    'lattice_name': {
        'mode_name': {
            'xlim': (min, max),
            'ylim': (min, max),
            'ticks': [tick1, tick2, ...]
        }
    }
}
"""

CONFIG = {
    'square': {
        'walk': {
            'xlim': (0.33, 0.37),
            'ylim': (0.33, 0.37),
            'ticks': [0.33, 0.34, 0.35, 0.36, 0.37]
        },
        'trail': {
            'xlim': (0.33, 0.35),
            'ylim': (0.33, 0.35),
            'ticks': [0.33, 0.335, 0.34, 0.345, 0.35]
        }
    },
    'simple-cubic': {
        'walk': {
            'xlim': (0.195, 0.2136),
            'ylim': (0.195, 0.2136),
            'zlim': (0.195, 0.2136)
        },
        'trail': {
            'xlim': (0.1975, 0.2045),
            'ylim': (0.1975, 0.2045),
            'zlim': (0.1975, 0.2045)
        }
    }
}

def get_config(lattice_name: str, mode: str):
    """
    Retrieves the inset/local plot configuration for a given lattice and mode.
    Returns None if no specific configuration is found.
    """
    return CONFIG.get(lattice_name, {}).get(mode)