"""
Configuration settings for plots generated by main.py.
Structure:
CONFIG = {
    'lattice_name': {
        'mode_name': {
            'xlim': (min, max),
            'ylim': (min, max),
            'zlim': (min, max)  # Optional, only for 3D plots
        }
    }
}
"""

CONFIG = {
    'square': {
        'walk': {
            'xlim': (0.33, 0.37),
            'ylim': (0.33, 0.37)
        },
        'trail': {
            'xlim': (0.33, 0.35),
            'ylim': (0.33, 0.35)
        }
    },
    'simple-cubic': {
        'walk': {
            'xlim': (0.195, 0.2136),
            'ylim': (0.195, 0.2136),
            'zlim': (0.195, 0.2136)
        },
        'trail': {
            'xlim': (0.1975, 0.2045),
            'ylim': (0.1975, 0.2045),
            'zlim': (0.1975, 0.2045)
        }
    }
}

_DEFAULT_CONFIG = {
    'xlim': (0, 1),
    'ylim': (0, 1),
    'zlim': (0, 1)  # Default for 3D plots
}

def get_config(lattice_name: str, mode: str):
    """
    Retrieves the inset/local plot configuration for a given lattice and mode.
    Returns _DEFAULT_CONFIG if no configuration is found.
    """
    config = CONFIG.get(lattice_name, {}).get(mode)
    if config is None:
        print(f"WARNING: inset/local plot is not configured for lattice '{lattice_name}' in mode '{mode}'.")
        return _DEFAULT_CONFIG
    else:
        return config
